credentials:
  usernames:
    admin:
      email: admin@draup.com
      name: System Administrator
      password: $2b$12$8kK8K8K8K8K8K8K8K8K8K8K8K8K8K8K8K8K8K8K8K8K8K8K8K8K8K8  # admin123
      role: admin
      plan: enterprise
      created_date: 2025-01-01
    demo_user:
      email: demo@example.com
      name: Demo User
      password: $2b$12$9lL9L9L9L9L9L9L9L9L9L9L9L9L9L9L9L9L9L9L9L9L9L9L9L9L9L9  # demo123
      role: user
      plan: basic
      created_date: 2025-01-01

cookie:
  expiry_days: 30
  key: draup_priority_tools_key
  name: draup_priority_tools_cookie

preauthorized:
  emails:
  - admin@draup.com